profiles:
  default:
    load_balancing: random
    log_queries: 1
    max_execution_time: 180
    exchange_timeout_ms: 300000
    cnch_data_retention_time_in_sec: 10
    s3_gc_batch_size: 10
    enable_lazy_load_data_parts: 1
  point_lookup:
    max_threads: 1
    exchange_source_pipeline_threads: 1
    enable_plan_cache: true
    query_worker_fault_tolerance: false
    send_cacheable_table_definitions: true
    optimize_skip_unused_shards: true
    enable_prune_source_plan_segment: true
users:
  default:
    networks:
      ip: ::/0
    password: ""
    profile: default
    quota: default
  server:
    networks:
      ip: ::/0
    password: ""
    profile: default
    quota: default
  probe:
    networks:
      ip: ::/0
    password: ""
    profile: default
    quota: default

quotas:
  default:
    interval:
      duration: 3600
      queries: 0
      errors: 0
      result_rows: 0
      read_rows: 0
      execution_time: 0
