logger:
  level: trace
  log: /var/log/byconity/out.log
  errorlog: /var/log/byconity/err.log
  testlog: /var/log/byconity/test.log
  size: 1000M
  count: 10
http_port: 21557
rpc_port: 30605
tcp_port: 52145
ha_tcp_port: 26247
exchange_port: 47447
exchange_status_port: 60611
interserver_http_port: 30491
listen_host: "0.0.0.0"
cnch_type: server
max_connections: 4096
keep_alive_timeout: 3
max_concurrent_queries: 200
uncompressed_cache_size: 8589934592
mark_cache_size: 5368709120
path: /var/byconity/
tmp_path: /var/byconity/tmp_data/
users_config: /config/users.yml
default_profile: default
default_database: default
timezone: Europe/Moscow
mlock_executable: false
macros:
  "-incl": macros
  "-optional": true
builtin_dictionaries_reload_interval: 3600
max_session_timeout: 3600
default_session_timeout: 60
dictionaries_config: "*_dictionary.xml"
format_schema_path: /var/byconity/format_schemas/
perQuery: 1
daemon_manager:
  port: 17553
  daemon_jobs:
    job:
      - name: PART_GC
        interval: 10000
        disable: 0
      - name: PART_MERGE
        interval: 10000
        disable: 0
      - name: CONSUMER
        interval: 10000
        disable: 0
      - name: GLOBAL_GC
        interval: 5000
        disable: 1
      - name: PART_CLUSTERING
        interval: 30000
        disable: 0
      - name: DEDUP_WORKER
        interval: 3000
        disable: 0
      # Increasing the frequency of recycling in a test environment
      - name: TXN_GC
        interval: 3000
        disable: 0
